### ISSUE TITLE
Move user objects to their own class file.

### ISSUE THREAD

**Issue by badstreff** [BadStreff/COSC3318-Questionnaire#1]
Currently the user methods are part of the main db package, they will need to be split off to their own object class. The current methods are: authenticateUser(), createUser(), and hashPassword()

createUser will become the constructor for the new class.

In addition the database core class will need 2 new methods added: addUser() and deleteUser()

Variables in the new user class should match columns in the database schema.

**Comment by JaBase** [comment]
With help from Corey <3
