### ISSUE TITLE
Front End Signup Page - Add Checking

### ISSUE THREAD

**Issue by badstreff** [BadStreff/COSC3318-Questionnaire#16]
A check will need to be done for valid email addresses, passwords match, username not taken etc...

Some of this can be done in javascript and some will need done on the back end.

**Comment by badstreff** [comment]
The user should also receive a response back if a signup fails or if passwords do not match.

**Comment by talhusain** [comment]
found some code that will help me with this, I'll try to get it done soon

**Comment by badstreff** [comment]
Implemented.
