### ISSUE TITLE
Add javascript to clear auth cookie when clicking signout

### ISSUE THREAD

**Issue by badstreff** [BadStreff/COSC3318-Questionnaire#17]
The cookie 'uid' should be cleared when the sign out button is pressed. This lets the web server know that the user is no longer logged in.

**Comment by badstreff** [comment]
This page should help.

http://stackoverflow.com/questions/3671659/jquery-delete-cookies

**Comment by talhusain** [comment]
I may just not be seeing it, but is the Sign out button already coded? or do i need to code that too?

**Comment by talhusain** [comment]
Done. 1% Al, 99% Adam. Lol
