### ISSUE TITLE
Create A View for Questions that Have no been Answered by a Particular User

### ISSUE THREAD

**Issue by badstreff** [BadStreff/COSC3318-Questionnaire#21]
This should be done in the db.database class.

**Comment by badstreff** [comment]
This should just be a single SQL statement, under the createTable() method. 

This page should be helpful: http://www.w3schools.com/sql/sql_view.asp

**Comment by talhusain** [comment]
tried working on this, but hit a road block, if you wanna help me figure out what I did wrong, awesome, if you just wanna do it yourself, also awesome lol.

**Comment by badstreff** [comment]
You can go ahead and close it, as it would take too much space and we have implemented this functionality in the getRandomQuestion() method

**Comment by talhusain** [comment]
Sounds good. Closed.
